/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaListAllNodesFilter extends MegaNodeScopeFilter {
  private transient long swigCPtr;

  protected MegaListAllNodesFilter(long cPtr, boolean cMemoryOwn) {
    super(megaJNI.MegaListAllNodesFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaListAllNodesFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaListAllNodesFilter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaListAllNodesFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MegaListAllNodesFilter createInstance() {
    long cPtr = megaJNI.MegaListAllNodesFilter_createInstance();
    return (cPtr == 0) ? null : new MegaListAllNodesFilter(cPtr, true);
  }

   MegaNodeScopeFilter copy() {
    long cPtr = megaJNI.MegaListAllNodesFilter_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaListAllNodesFilter(cPtr, true);
  }

  public void byTimestampAnchor(long startDate, long endDate, int sectionOrder) {
    megaJNI.MegaListAllNodesFilter_byTimestampAnchor(swigCPtr, this, startDate, endDate, sectionOrder);
  }

  public long byTimestampAnchorStartDate() {
    return megaJNI.MegaListAllNodesFilter_byTimestampAnchorStartDate(swigCPtr, this);
  }

  public long byTimestampAnchorEndDate() {
    return megaJNI.MegaListAllNodesFilter_byTimestampAnchorEndDate(swigCPtr, this);
  }

  public int byTimestampAnchorOrder() {
    return megaJNI.MegaListAllNodesFilter_byTimestampAnchorOrder(swigCPtr, this);
  }

}
