/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaFileServiceReclaimOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaFileServiceReclaimOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaFileServiceReclaimOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaFileServiceReclaimOptions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaFileServiceReclaimOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaFileServiceReclaimOptions copy() {
    long cPtr = megaJNI.MegaFileServiceReclaimOptions_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaFileServiceReclaimOptions(cPtr, true);
  }

  public static MegaFileServiceReclaimOptions create() {
    long cPtr = megaJNI.MegaFileServiceReclaimOptions_create();
    return (cPtr == 0) ? null : new MegaFileServiceReclaimOptions(cPtr, true);
  }

  public int getAgeThreshold() {
    return megaJNI.MegaFileServiceReclaimOptions_getAgeThreshold(swigCPtr, this);
  }

  public void setAgeThreshold(int ageThreshold) {
    megaJNI.MegaFileServiceReclaimOptions_setAgeThreshold(swigCPtr, this, ageThreshold);
  }

  public SWIGTYPE_p_std__size_t getBatchSize() {
    return new SWIGTYPE_p_std__size_t(megaJNI.MegaFileServiceReclaimOptions_getBatchSize(swigCPtr, this), true);
  }

  public void setBatchSize(SWIGTYPE_p_std__size_t batchSize) {
    megaJNI.MegaFileServiceReclaimOptions_setBatchSize(swigCPtr, this, SWIGTYPE_p_std__size_t.getCPtr(batchSize));
  }

  public long getDelay() {
    return megaJNI.MegaFileServiceReclaimOptions_getDelay(swigCPtr, this);
  }

  public void setDelay(long seconds) {
    megaJNI.MegaFileServiceReclaimOptions_setDelay(swigCPtr, this, seconds);
  }

  public long getPeriod() {
    return megaJNI.MegaFileServiceReclaimOptions_getPeriod(swigCPtr, this);
  }

  public void setPeriod(long seconds) {
    megaJNI.MegaFileServiceReclaimOptions_setPeriod(swigCPtr, this, seconds);
  }

  public long getReclaimThreshold() {
    return megaJNI.MegaFileServiceReclaimOptions_getReclaimThreshold(swigCPtr, this);
  }

  public void setReclaimThreshold(long bytes) {
    megaJNI.MegaFileServiceReclaimOptions_setReclaimThreshold(swigCPtr, this, bytes);
  }

  public long getReclaimTarget() {
    return megaJNI.MegaFileServiceReclaimOptions_getReclaimTarget(swigCPtr, this);
  }

  public void setReclaimTarget(long bytes) {
    megaJNI.MegaFileServiceReclaimOptions_setReclaimTarget(swigCPtr, this, bytes);
  }

}
