/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaNodeScopeFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaNodeScopeFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaNodeScopeFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaNodeScopeFilter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaNodeScopeFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaNodeScopeFilter copy() {
    long cPtr = megaJNI.MegaNodeScopeFilter_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaNodeScopeFilter(cPtr, true);
  }

  public void byCategory(int mimeType) {
    megaJNI.MegaNodeScopeFilter_byCategory__SWIG_0(swigCPtr, this, mimeType);
  }

  public int byCategory() {
    return megaJNI.MegaNodeScopeFilter_byCategory__SWIG_1(swigCPtr, this);
  }

  public void byLocationHandles(MegaHandleList ancestorHandles) {
    megaJNI.MegaNodeScopeFilter_byLocationHandles__SWIG_0(swigCPtr, this, MegaHandleList.getCPtr(ancestorHandles), ancestorHandles);
  }

  public MegaHandleList byLocationHandles() {
    long cPtr = megaJNI.MegaNodeScopeFilter_byLocationHandles__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaHandleList(cPtr, false);
  }

  public void byExcludeLocationHandles(MegaHandleList excludeHandles) {
    megaJNI.MegaNodeScopeFilter_byExcludeLocationHandles__SWIG_0(swigCPtr, this, MegaHandleList.getCPtr(excludeHandles), excludeHandles);
  }

  public MegaHandleList byExcludeLocationHandles() {
    long cPtr = megaJNI.MegaNodeScopeFilter_byExcludeLocationHandles__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaHandleList(cPtr, false);
  }

  public void byLocation(int scope) {
    megaJNI.MegaNodeScopeFilter_byLocation__SWIG_0(swigCPtr, this, scope);
  }

  public int byLocation() {
    return megaJNI.MegaNodeScopeFilter_byLocation__SWIG_1(swigCPtr, this);
  }

  public void bySensitivity(int filterOption) {
    megaJNI.MegaNodeScopeFilter_bySensitivity__SWIG_0(swigCPtr, this, filterOption);
  }

  public int bySensitivity() {
    return megaJNI.MegaNodeScopeFilter_bySensitivity__SWIG_1(swigCPtr, this);
  }

  public final static int SENSITIVITY_SHOW_ALL = 0;
  public final static int SENSITIVITY_HIDE_SENSITIVE = 1;

  public final static int LOCATION_CLOUD_DRIVE = 0;
  public final static int LOCATION_CLOUD_DRIVE_AND_VAULT = 1;
  public final static int LOCATION_CLOUD_DRIVE_VAULT_AND_RUBBISH = 2;

  public final static long MAX_LOCATION_HANDLES = 3;
}
