/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaDateSection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaDateSection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaDateSection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaDateSection obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaDateSection(swigCPtr);
      }
      swigCPtr = 0;
    }
}

   MegaDateSection copy() {
    long cPtr = megaJNI.MegaDateSection_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaDateSection(cPtr, true);
  }

  public String getGroupId() {
    return megaJNI.MegaDateSection_getGroupId(swigCPtr, this);
  }

  public long getStartDate() {
    return megaJNI.MegaDateSection_getStartDate(swigCPtr, this);
  }

  public long getEndDate() {
    return megaJNI.MegaDateSection_getEndDate(swigCPtr, this);
  }

  public long getCount() {
    return megaJNI.MegaDateSection_getCount(swigCPtr, this);
  }

}
