/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaGroupNodesByDateFilter extends MegaNodeScopeFilter {
  private transient long swigCPtr;

  protected MegaGroupNodesByDateFilter(long cPtr, boolean cMemoryOwn) {
    super(megaJNI.MegaGroupNodesByDateFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaGroupNodesByDateFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaGroupNodesByDateFilter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaGroupNodesByDateFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MegaGroupNodesByDateFilter createInstance() {
    long cPtr = megaJNI.MegaGroupNodesByDateFilter_createInstance();
    return (cPtr == 0) ? null : new MegaGroupNodesByDateFilter(cPtr, true);
  }

   MegaNodeScopeFilter copy() {
    long cPtr = megaJNI.MegaGroupNodesByDateFilter_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaGroupNodesByDateFilter(cPtr, true);
  }

  public void byGranularity(int granularity) {
    megaJNI.MegaGroupNodesByDateFilter_byGranularity__SWIG_0(swigCPtr, this, granularity);
  }

  public int byGranularity() {
    return megaJNI.MegaGroupNodesByDateFilter_byGranularity__SWIG_1(swigCPtr, this);
  }

  public final static int SECTION_GRANULARITY_DAY = 0;
  public final static int SECTION_GRANULARITY_MONTH = 1;
  public final static int SECTION_GRANULARITY_YEAR = 2;

}
