/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nz.mega.sdk;

public class MegaSearchCursorOffset {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MegaSearchCursorOffset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaSearchCursorOffset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MegaSearchCursorOffset obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  protected synchronized void delete() {   
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaSearchCursorOffset(swigCPtr);
      }
      swigCPtr = 0;
    }
}

  public static MegaSearchCursorOffset createInstance() {
    long cPtr = megaJNI.MegaSearchCursorOffset_createInstance();
    return (cPtr == 0) ? null : new MegaSearchCursorOffset(cPtr, false);
  }

   MegaSearchCursorOffset copy() {
    long cPtr = megaJNI.MegaSearchCursorOffset_copy(swigCPtr, this);
    return (cPtr == 0) ? null : new MegaSearchCursorOffset(cPtr, false);
  }

  public void setLastName(String lastName) {
    megaJNI.MegaSearchCursorOffset_setLastName(swigCPtr, this, lastName);
  }

  public void setLastHandle(long lastHandle) {
    megaJNI.MegaSearchCursorOffset_setLastHandle(swigCPtr, this, lastHandle);
  }

  public void setLastSize(long lastSize) {
    megaJNI.MegaSearchCursorOffset_setLastSize(swigCPtr, this, lastSize);
  }

  public void setLastMtime(long lastMtime) {
    megaJNI.MegaSearchCursorOffset_setLastMtime(swigCPtr, this, lastMtime);
  }

  public void setLastLabel(int lastLabel) {
    megaJNI.MegaSearchCursorOffset_setLastLabel(swigCPtr, this, lastLabel);
  }

  public void setLastFav(int lastFav) {
    megaJNI.MegaSearchCursorOffset_setLastFav(swigCPtr, this, lastFav);
  }

  public String getLastName() {
    return megaJNI.MegaSearchCursorOffset_getLastName(swigCPtr, this);
  }

  public long getLastHandle() {
    return megaJNI.MegaSearchCursorOffset_getLastHandle(swigCPtr, this);
  }

  public long getLastSize() {
    return megaJNI.MegaSearchCursorOffset_getLastSize(swigCPtr, this);
  }

  public long getLastMtime() {
    return megaJNI.MegaSearchCursorOffset_getLastMtime(swigCPtr, this);
  }

  public int getLastLabel() {
    return megaJNI.MegaSearchCursorOffset_getLastLabel(swigCPtr, this);
  }

  public int getLastFav() {
    return megaJNI.MegaSearchCursorOffset_getLastFav(swigCPtr, this);
  }

}
